import type { PostIt } from "@/lib/types";

export const SAMPLE_POSTS: PostIt[] = [
  {
    id: "demo-1",
    text: "Finally wrapped my brain around restaking. Feeling unstoppable tonight!",
    color: "var(--post-it-purple)",
    signature: "@eth_enthusiast",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    hearts: 12,
    position: 1,
    ipHash: null,
    shares: 3,
  },
  {
    id: "demo-2",
    text: "Confession: I walked into the SheFi call 15 minutes late but still asked the first question 😅",
    color: "var(--post-it-pink)",
    signature: null,
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    hearts: 8,
    position: 2,
    ipHash: null,
    shares: 1,
  },
  {
    id: "demo-3",
    text: "PSA: gas is wild today. Set a limit order and go sip a matcha. 💅",
    color: "var(--post-it-blue)",
    signature: "@matchaqueen",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    hearts: 21,
    position: 3,
    ipHash: null,
    shares: 5,
  },
  {
    id: "demo-4",
    text: "Win: onboarded my bestie to DeFi and she called yield farming “crypto gardening” 🌱",
    color: "var(--post-it-green)",
    signature: null,
    isAnonymous: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    hearts: 15,
    position: 4,
    ipHash: null,
    shares: 0,
  },
  {
    id: "demo-5",
    text: "Manifesting that SheFi NYC meetup energy every single day. You all keep me building.",
    color: "var(--post-it-yellow)",
    signature: "@gm_girl",
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    hearts: 18,
    position: 5,
    ipHash: null,
    shares: 4,
  },
];
